#include <adcgui.h>
#include "freertos.h"
#include "portmacro.h"
#include "queue.h"
#include <stdbool.h>

/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stdlib.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0   (GUI_ID_USER + 0x00)
#define ID_GRAPH_0   (GUI_ID_USER + 0x01)
#define ID_BUTTON_0         (GUI_ID_USER + 0X02)
#define ID_BUTTON_1         (GUI_ID_USER + 0X03)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static GRAPH_SCALE_Handle hScaleV;
static GRAPH_DATA_Handle ahData;
static int  stop_flag=0;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _AdcFrameCreate[] = {
	{ WINDOW_CreateIndirect, "WINDOW", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
	{ GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 10, 60, 750, 350, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button0", ID_BUTTON_0, 0, 0, 97, 34, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button1", ID_BUTTON_1, 703, 0, 97, 34, 0, 0x0, 0 },
// USER START (Optionally insert additional widgets)
// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _adcguicallback(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	WM_HTIMER hTimer;
	// USER START (Optionally insert additional variables)
	// USER END
	int     NCode;
	int     Id;
	WM_HWIN hWin = pMsg->hWin;
	//消息队列变量
	int adcmsg;
  BaseType_t err;
	extern QueueHandle_t Adc_Queue;

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:

	stop_flag=false;
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		BUTTON_SetText(hItem, "Back");
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		BUTTON_SetText(hItem, "Stop");

		
		hTimer= WM_CreateTimer(WM_GetClientWindow(hWin),1, 300, 0);//创建定时器
	
		(void)hTimer;//防止警告
		//
		// Initialization of 'Graph'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
		
	  /*创建数据对象*/
		ahData = GRAPH_DATA_YT_Create(GUI_GREEN, 750, 0,0);

		/*数据对象添加到图形控件*/
		GRAPH_AttachData(hItem, ahData);

		/*设置Y轴方向的栅格间距*/
		GRAPH_SetGridDistY(hItem,20);

		/*固定X轴方向的栅格间距*/
		GRAPH_SetGridFixedX(hItem, 1);

		/*设置栅格可见*/
		GRAPH_SetGridVis(hItem,1);

		/*创建刻度对象*/

		hScaleV = GRAPH_SCALE_Create(20,GUI_TA_RIGHT,GRAPH_SCALE_CF_VERTICAL,20);
		/*将垂直刻度对象添加到图形控件*/

		GRAPH_AttachScale(hItem,hScaleV);

		/*用于设置比例刻度因子*/
		GRAPH_SCALE_SetFactor(hScaleV,1);

		/*设置标签字体颜色*/
		GRAPH_SCALE_SetFont(hScaleV,GUI_FONT_16B_ASCII);
		GRAPH_SCALE_SetTextColor(hScaleV, GUI_RED);
		/*设置上下左右边界的大小*/

		GRAPH_SetBorder(hItem, 20, 10, 10, 10);
	
		
		
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
		
		
		case WM_PAINT:
		// USER START (Optionally insert additional message handling)
		// USER END
			break;
		
		case WM_TIMER:
			
		WM_RestartTimer(pMsg->Data.v,300); //窗口定时器重装填
		
		if (stop_flag!=true)
			{
			
			err=xQueueReceive(Adc_Queue,&adcmsg,portMAX_DELAY);
		
				if(err!=NULL)   	//消息禔dc_Queue创建成功
				{
				printf("消息接收成功\r\n");
				GRAPH_DATA_YT_AddValue(ahData, adcmsg/100);
				printf("the graph data is%d\r\n",adcmsg);
				}
			
			
			//GRAPH_DATA_YT_AddValue(ahData, rand() % 100); //测试
				
			}
		break;		
		case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;

		switch (Id) {
		case ID_BUTTON_0: // Notifications sent by 'Edit'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
			

				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				GUI_EndDialog(hWin, 0);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			
			}
		break;
		case ID_BUTTON_1: // Notifications sent by 'Edit'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
			

				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				
			  stop_flag=!stop_flag;
				
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			
			}
		break;
	}
		break;
		default:
		WM_DefaultProc(pMsg);
		break;
	
 }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN ADCCreateFramewin(void);
WM_HWIN ADCCreateFramewin(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_AdcFrameCreate, GUI_COUNTOF(_AdcFrameCreate), _adcguicallback, WM_HBKWIN, 0, 0);
	return hWin;
}




void App_ADC(WM_HWIN hWin)
{
	GUI_CreateDialogBox(_AdcFrameCreate,
		GUI_COUNTOF(_AdcFrameCreate),
		&_adcguicallback,
		hWin,
		0,
		0);
}

/*************************** End of file ****************************/


